[package]
name = "simonsev-chess-gui"
version = "0.1.0"
edition = "2021"

[lib]
name = "simonsev_chess_gui"
path = "src/gui.rs"

[dependencies]
fritiofr_chess = { git = "https://github.com/INDA23PlusPlus/fritiofr-chess" }
ggez = "0.9.3"

